development: &default
  adapter: trilogy
  encoding: utf8mb4
  collation: utf8mb4_bin
  host: <%= ENV.fetch('MARIADB_HOST', 'mysql') %>
  reconnect: true
  database: <%= ENV.fetch('MARIADB_DEV_DATABASE') %>
  pool: 5
  username: <%= ENV.fetch('MARIADB_USER') %>
  password: "<%= ENV.fetch('MARIADB_PASSWORD') %>"
  port: 3306

test:
  <<: *default
  database: <%= ENV.fetch('MARIADB_TEST_DATABASE').to_s %>

production:
  <<: *default
  database: <%= ENV.fetch('MARIADB_DATABASE').to_s %>
